server:
  port: 16771

link:
  kafka:
    bootStrapAddress: 192.168.0.131:9092
  spark:
    master: spark://192.168.0.132:7077
    stream:
      kafka:
        durations: 10

#spring:
#  kafka:
#    producer:
#      acks: -1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      compression-type: lz4
#      properties:
#        schema.registry.url: http://192.168.0.131:8081
#        enable:
#          idempotence: true
#    consumer:
#      group-id: clamos
#      enable-auto-commit: false
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      schema.registry.url: http://192.168.0.131:8081
#      isolation.level: read_committed

logging:
  level:
    root: info


eureka:
  instance:
    #    hostname: RL-PC
    #    ip-address: 192.168.0.135
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.49:8761/eureka/  #,http://192.168.0.141:8761/eureka/,http://192.168.0.142:8761/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: /mapper/**/*.xml